repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
    -  id: ruff
       args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.9.0'  # Use the sha / tag you want to point at
      hooks:
      -  id: mypy
         additional_dependencies: [pytest]


ci:
    autofix_prs: false
