[project]
name = "rebin"
version = "0.1.0"
description = "Re-bin JPEG2000 images"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "click",
    "dask",
    "glymur",
    "joblib",
    "numpy",
    "scikit-image",
]

[tool.uv]
dev-dependencies = [
    "pytest",
]
